export default {
  OPEN_PUBLISH: 'OPEN_PUBLISH',
  PUBLISH_IDEA: 'PUBLISH_IDEA',
  REQUEST_PUBLISH_IDEA: 'REQUEST_PUBLISH_IDEA',
  REQUEST_PUBLISH_IDEA_SUCCESS: 'REQUEST_PUBLISH_IDEA_SUCCESS',
  REQUEST_PUBLISH_IDEA_FAILURE: 'REQUEST_PUBLISH_IDEA_FAILURE',
};
