export default {
  OPEN_PUBLISH: 'OPEN_PUBLISH',

  CREATE_IDEA: 'PUBLISH_IDEA',
  CREATE_IDEA_SUCCESS: 'CREATE_IDEA_SUCCESS',
  CREATE_IDEA_FAILURE: 'CREATE_IDEA_FAILURE',

  TOGGLE_TAGS: 'TOGGLE_TAGS',
  CLEAR_TAGS: 'CLEAR_TAGS',

  LIST_IDEAS: 'LIST_IDEAS',
  LIST_IDEAS_SUCCESS: 'LIST_IDEAS_SUCCESS',
  LIST_IDEAS_FAILURE: 'LIST_IDEAS_FAILURE',

  GET_IDEA: 'GET_IDEA',
  GET_IDEA_SUCCESS: 'GET_IDEA_SUCCESS',
  GET_IDEA_FAILURE: 'GET_IDEA_FAILURE',

  LIKE_IDEA: 'LIKE_IDEA',
  LIKE_IDEA_SUCCESS: 'LIKE_IDEA_SUCCESS',
  LIKE_IDEA_FAILURE: 'LIKE_IDEA_FAILURE',

  UNLIKE_IDEA: 'UNLIKE_IDEA',
  UNLIKE_IDEA_SUCCESS: 'UNLIKE_IDEA_SUCCESS',
  UNLIKE_IDEA_FAILURE: 'UNLIKE_IDEA_FAILURE',

  LOAD_USER_IDEAS: 'LOAD_USER_IDEAS',
  LOAD_USER_IDEAS_SUCCESS: 'LOAD_USER_IDEAS_SUCCESS',
  LOAD_USER_IDEAS_FAILURE: 'LOAD_USER_IDEAS_FAILURE',
};
