export default {
  OPEN_COMMENT: 'OPEN_COMMENT',
  
  CREATE_COMMENT: 'CREATE_COMMENT',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',

  GET_COMMENT: 'GET_COMMENT',
  GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
  GET_COMMENT_FAILURE: 'GET_COMMENT_FAILURE',
};
