export default {
  OPEN_PUBLISH: 'OPEN_PUBLISH',
  PUBLISH_IDEA: 'PUBLISH_IDEA',
  REQUEST_PUBLISH_IDEA: 'REQUEST_PUBLISH_IDEA',
  REQUEST_PUBLISH_IDEA_SUCCESS: 'REQUEST_PUBLISH_IDEA_SUCCESS',
  REQUEST_PUBLISH_IDEA_FAILURE: 'REQUEST_PUBLISH_IDEA_FAILURE',

  TOGGLE_TAGS: 'toggle_tags',
  CLEAR_TAGS: 'clear_tags',
  CLEAR_FORMS: 'CLEAR_FORMS',
};
